name: mlgeo_sk
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - pyarrow
  - plotly
  - geopandas
  - matplotlib
  - numpy
  - scipy
  - pandas
  - rasterio
  - scikit-learn
  - shapely
  - xarray
  - h5py
  - netcdf4
  - zarr
  - nbgitpuller
  - wget
  - folium
  - geopandas
  - pycrs
  - pooch
  - obspy
  - seaborn
  - tsfresh
  - auto-sklearn
  - torch
  - torch-vision
  - pip=20
